INSERT INTO USER_ENTITY_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES (1,'amol@mail.com', 'Amol', '9764247074', 'test');

INSERT INTO USER_ENTITY_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES (2,'rutuja@mail.com', 'Rutuja', '9552434543', 'rutu');